name: My Project
on: push
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
       - name: Download Repository
         uses: actions/checkout@v4
       - name: Install Node
         uses: actions/setup-node@v4
         with:
            node-version: 20
       - name: Install Dependencies
         run: npm ci
       - name: Run Tests
         run: npm test
